language: java
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
notifications:
  email: false
install: mvn clean package install
deploy:
    provider: releases
    api-key: "$GITHUB_OATH_TOKEN"
    file:
        - "building/target/shout 1.0-SNAPSHOT.jar"
    skip_cleanup: true
    on:
        tags: true
        all_branches: true